
export const GymNames = {
  AlleJLM: 'Alle JLM',
  Home: 'Home',
  BoulderHaifa: 'Boulder Haifa',
  Octopus: 'Octopus',
  IclimbHaifa: 'Iclimb Haifa',
  IclimbRishon: 'Iclimb Rishon',
  IclimbTLV: 'Iclimb TLV',
  IclimbJER: 'Iclimb JER',
  IclimbManara: 'Iclimb Manara',
  IclimbHerz: 'Iclimb Herz',
  IclimbHaogen: 'Iclimb Haogen',
  Boulderland: 'Boulderland',
  VikingRaanana: 'Viking Raanana',
  VikingTLV: 'Viking TLV',
  MonkeysAsh: 'Monkeys Ash',
  MonkeysNetanya: 'Monkeys Netanya',
  PRockModi: 'PRock Modi',
  PRockBeerSheva: 'PRock Beer Sheva',
  PRockHaifa: 'PRock Haifa',
  PRockRegba: 'PRock Regba',
  PRockTLV: 'PRock TLV',
  Rujum: 'Rujum',
  Rokiz: 'Rokiz',
  Venga: 'Venga',
  Totem: 'Totem',
  Campus: 'Campus',
  Levin: 'Levin',
  UrbanJER: 'Urban JER',
  UrbanRehovot: 'Urban Rehovot',
  BlocTLV: 'Bloc TLV',
  BlocJER: 'Bloc JER',
  Checkmate: 'Checkmate',
  Gecko: 'Gecko',
  Isaac: 'Isaac',
  KI: 'KI',
  TheArch: 'The Arch',
  VauxEast: 'VauxEast',
  CityBouldering: 'City Bouldering',
  Westway: 'Westway',
  CanaryWall: 'CanaryWall',
  Stronghold: 'Stronghold',
  Others: 'Others',
  MonoBloc: 'MonoBloc',
  Margalef: 'Margalef',
  EinPrat: 'Ein Prat',
  Timna: 'Timna',
  Zanoach: 'Zanoach',
  Michmas: 'Michmas',
  Amud: 'Amud',
  Gita: 'Gita',
  Yonim: 'Yonim',
  Nezer: 'Nezer',
  Shakran: 'Shakran',
  BeitArie: 'Beit Arie',
  Gefet: 'Gefet',
  Neelam: 'Neelam',
  Nir: 'Nir',
  AmirKara: 'Amir Kara',
  Kisra: 'Kisra',
  BeitOren: 'Beit Oren',
  Ramon: 'Ramon',
} as const;

export type GymName = typeof GymNames[keyof typeof GymNames];

export const ClimbingStyles = {
  BOULDER: 'Boulder',
  LEAD: 'Lead',
  BOTH: 'Both',
} as const;

export type ClimbingStyle = typeof ClimbingStyles[keyof typeof ClimbingStyles];
